/*********************************************************
 **
 ** File  SDY1_specification_symbology_layer.h.cosimu
 **
** Specification File:  C:\Users\Bruna\Desktop\sp3\almost\tutorial-arduino-display\specification.sgfx
 **
 ** Automatically generated by SCADE Display CG Simu
 ** Version 6.6.2 (build i15)
 **
 ** Date of generation: 2016-11-26T11:09:01
 ** Command line: ScadeDisplayCGSimu.exe -outdir C:\Users\Bruna\Desktop\sp3\almost\SCADE\tutorial-arduino-display\KCG\SDY1_specification\Code -prefix SDY1_specification_ C:\Users\Bruna\Desktop\sp3\almost\tutorial-arduino-display\specification.sgfx C:\Users\Bruna\Desktop\sp3\almost\tutorial-arduino-display\texture_table.stt C:\Users\Bruna\Desktop\sp3\almost\tutorial-arduino-display\font_table.sft C:\Users\Bruna\Desktop\sp3\almost\tutorial-arduino-display\color_table.sct C:\Users\Bruna\Desktop\sp3\almost\tutorial-arduino-display\line_width_table.swt C:\Users\Bruna\Desktop\sp3\almost\tutorial-arduino-display\line_stipple_table.sst
 *********************************************************/

#ifndef _SDY1_SPECIFICATION_SYMBOLOGY_LAYER_H_COSIMU
#define _SDY1_SPECIFICATION_SYMBOLOGY_LAYER_H_COSIMU

#include "sgl_types.h"

/* Accessors */
#ifndef SDY1_specification_symbology_layer_G_temperature
#define SDY1_specification_symbology_layer_G_temperature(_C_) ((_C_)->temperature)
#define SDY1_specification_symbology_layer_S_temperature(_C_,_V_) (_C_)->temperature = (_V_)
#endif /* SDY1_specification_symbology_layer_G_temperature */
#ifndef SDY1_specification_symbology_layer_G_oxygen_saturation
#define SDY1_specification_symbology_layer_G_oxygen_saturation(_C_) ((_C_)->oxygen_saturation)
#define SDY1_specification_symbology_layer_S_oxygen_saturation(_C_,_V_) (_C_)->oxygen_saturation = (_V_)
#endif /* SDY1_specification_symbology_layer_G_oxygen_saturation */
#ifndef SDY1_specification_symbology_layer_G_respiratory_rate
#define SDY1_specification_symbology_layer_G_respiratory_rate(_C_) ((_C_)->respiratory_rate)
#define SDY1_specification_symbology_layer_S_respiratory_rate(_C_,_V_) (_C_)->respiratory_rate = (_V_)
#endif /* SDY1_specification_symbology_layer_G_respiratory_rate */
#ifndef SDY1_specification_symbology_layer_G_heart_rate
#define SDY1_specification_symbology_layer_G_heart_rate(_C_) ((_C_)->heart_rate)
#define SDY1_specification_symbology_layer_S_heart_rate(_C_,_V_) (_C_)->heart_rate = (_V_)
#endif /* SDY1_specification_symbology_layer_G_heart_rate */

/* Context type */
typedef struct
{
  /* ------------------------- inputs --------------------------- */
  SGLfloat temperature;
  SGLfloat oxygen_saturation;
  SGLfloat respiratory_rate;
  SGLfloat heart_rate;
} SDY1_specification_typ_symbology_layer;

#endif /* _SDY1_SPECIFICATION_SYMBOLOGY_LAYER_H_COSIMU */

/*********************************************************
 ** End of file
 ** End of generation: 2016-11-26T11:09:01
 *********************************************************/

