/*********************************************************
 **
 ** File  test_UA_1.c
 **
 ** Automatically generated by SCADE Suite UA Adaptor
 ** Version R17 (build i15)
 ** 
 ** Date of generation: 2016-11-19T21:15:14
 ** Command line: C:/Program Files (x86)/Esterel Technologies/SCADE R17/SCADE/bin/uaadaptor.exe -sdy C:\Dev\ces-65\socket_test\socket_test.sdy -n C:\Program Files (x86)\Esterel Technologies\SCADE R17\SCADE Display\config\a661_description\a661.xml -outdir C:/Dev/ces-65/socket_test/KCG -k C:/Dev/ces-65/socket_test/KCG/kcg_trace.xml -o test_UA_1 -i socket_test_interface.h -encoding ASCII C:\Users\Artur Pimentel\Documents\ITA\CES-65\DisplayTS04.sgfx
 *********************************************************/
#include "kcg_sensors.h"
#include "test_UA_1.h"
#include "test_UA_1_constants.h"
#include "test_UA_1_private.h"

/********************************************************************************************
 * Send messages to the A661 server                                                         *
 ********************************************************************************************/
 uaa_size test_UA_1_send(buffer_el msg[], 
  outC_test* scade_ctx,  extern_out_ctx_t * extern_ctx){
  uaa_size offset = 0;
  
  offset = offset + a661_com_layer_1(msg + offset, scade_ctx, extern_ctx);
  return offset ;
}

/********************************************************************************************
 * Receive notifications from the A661 server                                               *
 ********************************************************************************************/
uaa_size test_UA_1_receive(buffer_el buffer[],  uaa_size buffer_size, 
  void* scade_ctx,  extern_in_ctx_t * extern_ctx){
  /*  No input in SCADE Suite model, function intentionally left empty */
  return 0 ;
}

/********************************************************************************************
 * Clear notifications                                                                      *
 ********************************************************************************************/
void test_UA_1_receive_clear(void* scade_ctx,  extern_in_ctx_t * extern_ctx){
  
}

/*********************************************************
 ** End of file
 ** End of generation: 2016-11-19T21:15:14
 *********************************************************/

