/*********************************************************
 **
 ** File  test_UA_1_LAY_1.c
 **
 ** Automatically generated by SCADE Suite UA Adaptor
 ** Version R17 (build i15)
 ** 
 ** Date of generation: 2016-11-19T21:15:14
 ** Command line: C:/Program Files (x86)/Esterel Technologies/SCADE R17/SCADE/bin/uaadaptor.exe -sdy C:\Dev\ces-65\socket_test\socket_test.sdy -n C:\Program Files (x86)\Esterel Technologies\SCADE R17\SCADE Display\config\a661_description\a661.xml -outdir C:/Dev/ces-65/socket_test/KCG -k C:/Dev/ces-65/socket_test/KCG/kcg_trace.xml -o test_UA_1 -i socket_test_interface.h -encoding ASCII C:\Users\Artur Pimentel\Documents\ITA\CES-65\DisplayTS04.sgfx
 *********************************************************/
#include "kcg_sensors.h"
#include "test_UA_1.h"
#include "test_UA_1_constants.h"
#include "test_UA_1_private.h"

/* Perform UA Request for layer 1 */
A661_INTERNAL uaa_size a661_com_A661_CMD_UA_REQUEST_layer_1(buffer_el msg[], 
  outC_test* scade_ctx,  extern_out_ctx_t * extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->Emit){
    
    if (scade_ctx->Emit){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_8(msg + offset,
        A661_REQ_LAYER_VISIBLE, 0);
    }
  }
  return offset ;
}

/* Pack messages for layer 1 */
 uaa_size a661_com_layer_1(buffer_el msg[], 
  outC_test* scade_ctx,  extern_out_ctx_t* extern_ctx){
  uaa_size offset = 0;
  if (scade_ctx->Emit){
    LAYER("a661_layer#1");
    offset = 8;
    a661_msg_cmd_header(msg, 1, test_UA_1_DEFAULT_CONTEXT_NUMBER);
    if (scade_ctx->Emit){
      WIDGET("Victim_name_label#6");
      offset = offset + a661_com_csp_widget_Label(msg + offset, 6,
        scade_ctx->Emit, scade_ctx->Output1, scade_ctx->Output1);
    }
    if (scade_ctx->Emit){
      offset = offset + a661_com_A661_CMD_UA_REQUEST_layer_1(msg + offset,
        scade_ctx, extern_ctx);
    }
    WRITE_ULONG(msg + offset, A661_END_BLOCK);
    offset = offset + 4;
    WRITE_ULONG(msg + 4, offset);
  }
  return offset ;
}

/*********************************************************
 ** End of file
 ** End of generation: 2016-11-19T21:15:14
 *********************************************************/

